version: "3.9"
services:
  db:
    image: mysql:latest
    volumes:
      - /media/usb/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bighead4548
      MYSQL_DATABASE: windaninjasdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: Bighead4548
    networks:
      - backend
    ports:
      - "3306:3306"

  web:
    build:
      context: /media/usb/php-apache
      dockerfile: Dockerfile
    depends_on:
      - db

    volumes:
      - /media/usb/php-apache:/var/www/html
      - /home/ubuntu/certificates:/etc/apache2/ssl
      - /media/usb/apache/default-ssl.conf:/etc/apache2/sites-available/default-ssl.conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - frontend
      - backend
    environment:
      AWS_REGION: eu-west-2
      AWS_ACCESS_KEY_ID: AKIA3YC5GZJVUL5I2SQO
      AWS_SECRET_ACCESS_KEY: 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

networks:
  frontend:
  backend:
